site_name: utilities-py
site_description: A utilities library that exists.
site_author: Ethan Smurf

repo_url: https://github.com/TheChaosCommunity/utilities.py
edit_uri: https://github.com/TheChaosCommunity/utilities.py/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
